name = "unidancing"
main = "src/index.ts"
compatibility_date = "2022-07-23"
compatibility_flags = ["nodejs_compat"]

# [dev]
# port = 8787

[vars]
WORKER_ROOT = "https://connect.unidancing.art"
APP_ROOT = "https://unidancing.art"
