name = "unidance-coach"
main = "src/index.ts"
compatibility_date = "2022-07-23"

#[dev]
#port = 8787

[vars]
WORKER_ROOT = "https://unidance-coach.gossi.workers.dev"
APP_ROOT = "https://unidance-coach.pages.dev"

