name = "unidancing"
main = "src/index.ts"
compatibility_date = "2025-02-02"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
vars = { ENVIRONMENT = "dev", WORKER_ROOT = "http://localhost:8787", APP_ROOT = "http://localhost:4200", SPOTIFY_CLIENT_ID = "<SPOTIFY_CLIENT_ID>", SPOTIFY_CLIENT_SECRET = "<SPOTIFY_CLIENT_SECRET>", SENTRY_DSN = "<SENTRY_DSN>" }

# [dev]
# port = 8787

[observability]
enabled = true
head_sampling_rate = 1

[env.staging]
workers_dev = true
vars = { ENVIRONMENT = "staging", WORKER_ROOT = "https://connect.unidancing.art", APP_ROOT = "https://unidancing.art" }

[env.production]
vars = { ENVIRONMENT = "production", WORKER_ROOT = "https://connect.unidancing.art", APP_ROOT = "https://unidancing.art" }
